name: santa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: 
  url_launcher: 
  webview_flutter: 
  flutter_html: ^2.2.1
  google_maps_flutter: ^2.5.3
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.0
  flutter_map: 
  latlong2: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
